name: sesa
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::ignite
  - pip
  - pip:
    - pandas
    - transformers[torch]
    - sentencepiece
    - scikit-learn==0.24.0